//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alojamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alojamento()
        {
            this.EstadaAlojamentoes = new HashSet<EstadaAlojamento>();
            this.Tendas1 = new HashSet<Tenda>();
        }
    
        public decimal preço_base { get; set; }
        public string descrição { get; set; }
        public string localização { get; set; }
        public string nome { get; set; }
        public string nome_parque { get; set; }
        public decimal max_pessoas { get; set; }
    
        public virtual Parque Parque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadaAlojamento> EstadaAlojamentoes { get; set; }
        public virtual Bungalow Bungalow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tenda> Tendas1 { get; set; }
    }
}
