//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atividade
    {
        public decimal número { get; set; }
        public System.DateTime data_atividade { get; set; }
        public decimal preço { get; set; }
        public decimal lotação { get; set; }
        public string nome_atividade { get; set; }
        public string nome_parque { get; set; }
        public string descrição { get; set; }
    
        public virtual Parque Parque { get; set; }
    }
}
