//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bungallow
    {
        public string tipologia { get; set; }
        public string nome_alojamento { get; set; }
        public decimal preço_base { get; set; }
        public string descrição { get; set; }
        public string localização { get; set; }
        public string nome_parque { get; set; }
        public decimal max_pessoas { get; set; }
        public string email { get; set; }
        public string morada { get; set; }
        public Nullable<decimal> estrelas { get; set; }
    }
}
