//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponenteFatura
    {
        public decimal id { get; set; }
        public decimal id_fatura { get; set; }
        public string descrição { get; set; }
        public decimal preço { get; set; }
        public string tipo { get; set; }
    
        public virtual Fatura Fatura { get; set; }
    }
}
