//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fatura()
        {
            this.ComponenteFaturas = new HashSet<ComponenteFatura>();
        }
    
        public decimal id { get; set; }
        public decimal id_estada { get; set; }
        public string nome_hóspede { get; set; }
        public decimal nif_hóspede { get; set; }
        public Nullable<decimal> valor_final { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponenteFatura> ComponenteFaturas { get; set; }
        public virtual Estada Estada { get; set; }
        public virtual Hóspede Hóspede { get; set; }
    }
}
