//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HóspedeAtividade
    {
        public decimal nif_hóspede { get; set; }
        public string nome_atividade { get; set; }
        public string nome_parque { get; set; }
    
        public virtual Hóspede Hóspede { get; set; }
    }
}
